// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// HMMbvs
List HMMbvs(arma::mat datmat, arma::vec beta, arma::vec gamma, arma::vec nobs, arma::vec sp, IntegerVector klist, bool hmm, int iterations, double v1, double v2, int pt, int pe, double a, double b, int thin, int thin_hidden, int base01larger, int base00larger);
RcppExport SEXP _HMMbvs_HMMbvs(SEXP datmatSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP nobsSEXP, SEXP spSEXP, SEXP klistSEXP, SEXP hmmSEXP, SEXP iterationsSEXP, SEXP v1SEXP, SEXP v2SEXP, SEXP ptSEXP, SEXP peSEXP, SEXP aSEXP, SEXP bSEXP, SEXP thinSEXP, SEXP thin_hiddenSEXP, SEXP base01largerSEXP, SEXP base00largerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type datmat(datmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sp(spSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type klist(klistSEXP);
    Rcpp::traits::input_parameter< bool >::type hmm(hmmSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< double >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< int >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< int >::type pe(peSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type thin_hidden(thin_hiddenSEXP);
    Rcpp::traits::input_parameter< int >::type base01larger(base01largerSEXP);
    Rcpp::traits::input_parameter< int >::type base00larger(base00largerSEXP);
    rcpp_result_gen = Rcpp::wrap(HMMbvs(datmat, beta, gamma, nobs, sp, klist, hmm, iterations, v1, v2, pt, pe, a, b, thin, thin_hidden, base01larger, base00larger));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HMMbvs_HMMbvs", (DL_FUNC) &_HMMbvs_HMMbvs, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_HMMbvs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
