# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HMMbvs <- function(datmat, beta, gamma, nobs, sp, klist, hmm = TRUE, iterations = 5000L, v1 = 5, v2 = 1, pt = 30L, pe = 20L, a = 1, b = 9, thin = 10L, thin_hidden = 10L) {
    .Call(`_HMMbvs_HMMbvs`, datmat, beta, gamma, nobs, sp, klist, hmm, iterations, v1, v2, pt, pe, a, b, thin, thin_hidden)
}

